//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionHistory
    {
        public System.Guid ActionHistoryID { get; set; }
        public string description { get; set; }
        public string timestamp { get; set; }
        public int userid { get; set; }
    }
}
