//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealer
    {
        public Dealer()
        {
            this.Selling_History = new HashSet<Selling_History>();
            this.Products = new HashSet<Product>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
    
        public virtual ICollection<Selling_History> Selling_History { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
