//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EFLInventoryContainer : DbContext
    {
        public EFLInventoryContainer()
            : base("name=EFLInventoryContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<SubCategory> SubCategories { get; set; }
        public virtual DbSet<Transaction_Type> Transaction_Types { get; set; }
        public virtual DbSet<Transaction_History> Transaction_Histories { get; set; }
        public virtual DbSet<Dealer> Dealers { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ActionHistory> ActionHistories { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<MeasuringType> MeasuringTypes { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<ProductVariation> ProductVariations { get; set; }
        public virtual DbSet<DamagedProduct> DamagedProducts { get; set; }
    }
}
