//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductVariations = new HashSet<ProductVariation>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int brand_id { get; set; }
        public int dealer_id { get; set; }
        public int Category_id { get; set; }
        public int subCategory_id { get; set; }
        public bool status { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime last_updated { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual Dealer Dealer { get; set; }
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductVariation> ProductVariations { get; set; }
    }
}
