//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVariation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductVariation()
        {
            this.weight = 0.00m;
            this.cost_price = 0.00m;
            this.retail_price = 0.00m;
            this.wholesale_price = 0.00m;
            this.stock_threshold = 0;
            this.stock = 0;
            this.Transaction_Histories = new HashSet<Transaction_History>();
            this.DamagedProducts = new HashSet<DamagedProduct>();
        }
    
        public System.Guid VariationID { get; set; }
        public int Product_id { get; set; }
        public string VariationName { get; set; }
        public string image_url { get; set; }
        public int measured_by { get; set; }
        public decimal weight { get; set; }
        public decimal cost_price { get; set; }
        public decimal retail_price { get; set; }
        public decimal wholesale_price { get; set; }
        public int stock_threshold { get; set; }
        public int stock { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime last_updated { get; set; }
    
        public virtual MeasuringType MesuringType { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction_History> Transaction_Histories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DamagedProduct> DamagedProducts { get; set; }
    }
}
