//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_History
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction_History()
        {
            this.credit = 0.00m;
            this.debit = 0.00m;
            this.balance_due = 0.00m;
            this.change = 0.00m;
        }
    
        public int id { get; set; }
        public System.Guid ProductVariationVariationID { get; set; }
        public string dealer { get; set; }
        public int quantity { get; set; }
        public decimal credit { get; set; }
        public decimal debit { get; set; }
        public decimal balance_due { get; set; }
        public decimal change { get; set; }
        public string payment_type { get; set; }
        public System.DateTime payment_date { get; set; }
        public string remarks { get; set; }
        public string transaction_type { get; set; }
    
        public virtual ProductVariation ProductVariation { get; set; }
    }
}
