//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Type
    {
        public Transaction_Type()
        {
            this.Selling_History = new HashSet<Selling_History>();
        }
    
        public int id { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<Selling_History> Selling_History { get; set; }
    }
}
